# fly.toml app configuration file generated for ireland-on-reddit on 2024-02-14T12:25:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ireland-on-reddit'
primary_region = 'ewr'

[build]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
